### ISSUE TITLE
correction for Fig_4_15.m

### ISSUE THREAD

**Issue by fs446** [JensAhrens/soundfieldsynthesis#1]
correct version of line 38

D = sqrt( 8*pi .* k .* y_ref / i ) .*  cos( theta_pw - alpha_0  ) .* exp( -1i .* k .* cos( theta_pw - alpha_0 ) ) ;

would be

D = - sqrt( 8*pi .* 1i .* k .* y_ref ) .*  cos( theta_pw - alpha_0  ) .* exp( -1i .* k .* R .*cos( theta_pw - alpha_0 ) ) ;

most important is missing R in the last exp()

**Comment by JensAhrens** [comment]
Fixed. Thanks!
